name: build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -xe {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MRUBY_VERSION: 3.1.0
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install rake bison git gperf
      - name: Clone mruby
        run: git clone https://github.com/mruby/mruby.git
      - name: Copy build file
        run: cp -fp ./build_config.rb ./mruby/build_config.rb
      - name: Test
        working-directory: mruby
        run: rake all test
      - name: Build x86_64-linux-musl
        env:
          MRUBY_BUILD_TARGET: x86_64-linux-musl
        working-directory: mruby
        run: rake all test
      - name: Build aarch64-linux-musl
        env:
          MRUBY_BUILD_TARGET: aarch64-linux-musl
        working-directory: mruby
        run: rake all test
