name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

defaults:
  run:
    shell: bash -xe {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MRUBY_VERSION: 3.1.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - name: Build x86_64-linux-musl
        env:
          MRUBY_BUILD_TARGET: x86_64-linux-musl
        run: rake
      - name: Upload x86_64-linux-musl build
        uses: actions/upload-artifact@v4
        with:
          name: minierb-x86_64-linux-musl
          path: ./mruby/build/x86_64-linux-musl/bin/minierb
          retention-days: 1
      - name: Build aarch64-linux-musl
        env:
          MRUBY_BUILD_TARGET: aarch64-linux-musl
        run: rake
      - name: Upload aarch64-linux-musl build
        uses: actions/upload-artifact@v4
        with:
          name: minierb-aarch64-linux-musl
          path: ./mruby/build/aarch64-linux-musl/bin/minierb
          retention-days: 1

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: rake
      - name: Upload x86_64-darwin build
        uses: actions/upload-artifact@v4
        with:
          name: minierb-x86_64-darwin
          path: ./mruby/build/host/bin/minierb
          retention-days: 1
  build-macos-m1:
    runs-on: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: rake
      - name: Upload aarch64-darwin build
        uses: actions/upload-artifact@v4
        with:
          name: minierb-aarch64-darwin
          path: ./mruby/build/host/bin/minierb
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos
      - build-macos-m1
    permissions:
      contents: write

    steps:
      - name: Download x86_64-linux-musl build
        uses: actions/download-artifact@v4
        with:
          name: minierb-x86_64-linux-musl
          path: x86_64-linux-musl
      - name: Download aarch64-linux-musl build
        uses: actions/download-artifact@v4
        with:
          name: minierb-aarch64-linux-musl
          path: aarch64-linux-musl
      - name: Download x86_64-darwin build
        uses: actions/download-artifact@v4
        with:
          name: minierb-x86_64-darwin
          path: x86_64-darwin
      - name: Download aarch64-darwin build
        uses: actions/download-artifact@v4
        with:
          name: minierb-aarch64-darwin
          path: aarch64-darwin
      - name: Archive
        run: |
          gzip -c x86_64-linux-musl/minierb > minierb-x86_64-linux-musl.gz
          gzip -c aarch64-linux-musl/minierb > minierb-aarch64-linux-musl.gz
          gzip -c x86_64-darwin/minierb > minierb-x86_64-darwin.gz
          gzip -c aarch64-darwin/minierb > minierb-aarch64-darwin.gz
          sha256sum *.gz > checksums.txt
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.gz,checksums.txt"
